"""DO NOT EDIT THIS FILE"""

import sys
from config import environments_config_dict
from src.core.web import app as flask_app
from src.webapp.controllers import *
from src.__main__ import (
    start_webapp,
    _DEBUG,
    _PRODUCTION,
    _DEVELOPMENT
)

if __name__ == "__main__":
    start_arguments = sys.argv[1:]
    start_mode = start_arguments[0].upper() if len(start_arguments) >=1 else _DEVELOPMENT

    if start_mode == _DEBUG:
        start_webapp(app=flask_app, mode=_DEBUG, config_dict=environments_config_dict)
    elif start_mode == _PRODUCTION:
        start_webapp(app=flask_app, mode=_PRODUCTION, config_dict=environments_config_dict)
    else:
        start_webapp(app=flask_app)